import os
import datetime
import re
from fpdf import FPDF
# pyrefly: ignore [missing-import]
from docx import Document
from io import BytesIO

def _build_markdown_content(response_text: str) -> str:
    return f"""# AI Travel Plan

# **Generated:** {datetime.datetime.now().strftime('%Y-%m-%d at %H:%M')}  
# **Created by:** Anmol's AI Travel Agent

---

{response_text}

---

*This travel plan was generated by AI. Please verify all information, especially prices, operating hours, and travel requirements before your trip.*
"""


# Map of common Unicode chars that FPDF/latin-1 cannot encode -> safe ASCII replacements
_UNICODE_REPLACEMENTS = {
    '\u20b9': 'Rs.',
    '\u20ac': 'EUR',
    '\u00a3': 'GBP',
    '\u00a5': 'JPY',
    '\u20a9': 'KRW',
    '\u20ba': 'TRY',
    '\u20aa': 'ILS',
    '\u2248': '~',
    '\u2192': '->',
    '\u2190': '<-',
    '\u2013': '-',
    '\u2014': '--',
    '\u201c': '"',
    '\u201d': '"',
    '\u2018': "'",
    '\u2019': "'",
    '\u2026': '...',
    '\u2022': '*',
    '\u2713': 'yes',
    '\u2717': 'no',
    '\u00d7': 'x',
    '\u00b0': ' deg',
}


def _sanitize_for_pdf(text: str) -> str:
    """Replace common Unicode characters that latin-1 cannot encode."""
    for char, replacement in _UNICODE_REPLACEMENTS.items():
        text = text.replace(char, replacement)
    # Final fallback: drop any remaining non-latin-1 characters
    return text.encode('latin-1', errors='replace').decode('latin-1')


def _write_inline_markdown(pdf: FPDF, text: str) -> None:
    text = _sanitize_for_pdf(text)
    segments = re.split(r"(\*\*.*?\*\*)", text)
    for segment in segments:
        if segment.startswith("**") and segment.endswith("**") and len(segment) > 4:
            pdf.set_font("Arial", "B", pdf.font_size_pt)
            pdf.write(5, segment[2:-2])
        else:
            pdf.set_font("Arial", "", pdf.font_size_pt)
            pdf.write(5, segment)


def _write_markdown_to_pdf(pdf: FPDF, markdown_content: str) -> None:
    for line in markdown_content.splitlines():
        stripped = line.strip()
        if not stripped:
            pdf.ln(5)
            continue

        heading_match = re.match(r"^(#{1,6})\s+(.*)", stripped)
        if heading_match:
            level = len(heading_match.group(1))
            text = heading_match.group(2).strip()
            if level == 1:
                pdf.set_font("Arial", "B", 16)
            elif level == 2:
                pdf.set_font("Arial", "B", 14)
            else:
                pdf.set_font("Arial", "B", 12)
            _write_inline_markdown(pdf, text)
            pdf.ln(8)
            continue

        pdf.set_font("Arial", "", 11)
        _write_inline_markdown(pdf, stripped)
        pdf.ln(5)


def save_document(response_text: str, directory: str = "./output"):
    """Export travel plan to Markdown file with proper formatting"""
    os.makedirs(directory, exist_ok=True)
    markdown_content = _build_markdown_content(response_text)
    try:
        timestamp = datetime.datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
        filename = f"{directory}/Agentic_AI_Project_Krish_Naik{timestamp}.md"
        with open(filename, 'w', encoding='utf-8') as f:
            f.write(markdown_content)
        return filename
    except Exception as e:
        print(f"Error saving markdown file: {e}")
        return None


def save_document_pdf(response_text: str, directory: str = "./output"):
    """Export travel plan to PDF file, preserving bold and heading formatting."""
    os.makedirs(directory, exist_ok=True)
    markdown_content = _build_markdown_content(response_text)
    try:
        timestamp = datetime.datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
        filename = f"{directory}/Agentic_AI_Project_Krish_Naik{timestamp}.pdf"
        pdf = FPDF('P', 'mm', 'A4')
        pdf.set_auto_page_break(auto=True, margin=15)
        pdf.add_page()
        pdf.set_font("Arial", "", 11)
        _write_markdown_to_pdf(pdf, markdown_content)
        pdf.output(filename)
        return filename
    except Exception as e:
        print(f"Error saving PDF file: {e}")
        return None


def build_pdf_bytes(response_text: str) -> bytes:
    """Build PDF bytes for direct download."""
    markdown_content = _build_markdown_content(response_text)
    pdf = FPDF('P', 'mm', 'A4')
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    pdf.set_font("Arial", "", 11)
    _write_markdown_to_pdf(pdf, markdown_content)
    return pdf.output(dest='S').encode('latin-1')


def build_word_bytes(response_text: str) -> bytes:
    """Convert markdown response text to a .docx file in memory and return its bytes.
    This function parses simple markdown for headings, bold text, and tables.
    """
    markdown = _build_markdown_content(response_text)
    doc = Document()

    lines = markdown.splitlines()
    i = 0
    while i < len(lines):
        line = lines[i].rstrip()
        # Heading detection
        heading_match = re.match(r"^(#{1,6})\s+(.*)", line)
        if heading_match:
            level = len(heading_match.group(1))
            text = heading_match.group(2).strip()
            doc.add_heading(text, level=level)
            i += 1
            continue
        # Table detection
        if line.startswith('|') and line.endswith('|'):
            table_lines = []
            while i < len(lines) and lines[i].startswith('|') and lines[i].endswith('|'):
                table_lines.append(lines[i])
                i += 1
            if len(table_lines) >= 2 and re.match(r"^\|?\s*[-:]+\s*(\|\s*[-:]+\s*)*\|?$", table_lines[1]):
                header = [cell.strip() for cell in table_lines[0].split('|')[1:-1]]
                rows = []
                for row_line in table_lines[2:]:
                    rows.append([cell.strip() for cell in row_line.split('|')[1:-1]])
                table = doc.add_table(rows=1 + len(rows), cols=len(header))
                hdr_cells = table.rows[0].cells
                for idx, cell_text in enumerate(header):
                    paragraph = hdr_cells[idx].paragraphs[0]
                    run = paragraph.add_run(cell_text)
                    run.bold = True
                for r_idx, row in enumerate(rows, start=1):
                    row_cells = table.rows[r_idx].cells
                    for c_idx, cell_text in enumerate(row):
                        row_cells[c_idx].text = cell_text
                continue
        # Normal paragraph
        if line:
            parts = re.split(r"(\*\*.*?\*\*)", line)
            para = doc.add_paragraph()
            for part in parts:
                if part.startswith("**") and part.endswith("**"):
                    run = para.add_run(part[2:-2])
                    run.bold = True
                else:
                    para.add_run(part)
        else:
            doc.add_paragraph('')
        i += 1
    byte_io = BytesIO()
    doc.save(byte_io)
    return byte_io.getvalue()
